<?php
$requestUrl = $block->getUrl('dropdown/index/index');
?>
<select class="custom" id="category" style="width:40%">
    <option value="">Select Category...</option>
     <option value="">Exercise & Fitness</option>
      <option value="">Cricket</option>
       <option value="">Foot Ball</option>
</select>
<br/><br/>
<button id="getvaluebtn" title="Save" type="button" class="action-default scalable action-save action-secondary">
    <span> Selected Category </span>
</button>
